import type { ExperienceEntry } from '@/types';

/**
 * Career timeline, newest first.
 *
 * Source of truth: `Nitin_Bahunadam_GenAI_Resume` and the `Complete Career
 * Story` document. Nothing here is embellished beyond those two documents —
 * the copy expands on wording, never on scope, employers or outcomes.
 */
export const EXPERIENCE: ExperienceEntry[] = [
  {
    id: 'amex',
    kind: 'work',
    company: 'American Express',
    role: 'Full Stack Java & Generative AI Engineer',
    location: 'Phoenix, Arizona',
    period: 'Feb 2025 — Present',
    start: '2025-02',
    end: null,
    accent: 'electric',
    headline:
      'Building an internal Generative AI Knowledge Assistant on top of a secure enterprise Java platform.',
    summary: [
      'Contributed to the design and implementation of an Internal Generative AI Knowledge Assistant that lets authorized employees ask natural-language questions and receive source-grounded answers from approved enterprise documentation.',
      'Owned the Python/FastAPI side of the system — document ingestion, chunking, embeddings, retrieval, prompt orchestration, response validation and structured outputs — and the Java-to-Python contracts that connect it to existing Spring Boot enterprise services.',
    ],
    highlights: [
      'Built document-ingestion pipelines across PDFs, Word files, internal guides, policies and operating procedures, with OCR for scanned and image-based documents.',
      'Implemented recursive and semantic chunking with version-aware metadata schemas covering source, category, section, page, access classification and revision.',
      'Generated and indexed embeddings in Pinecone to support semantic discovery across approved knowledge sources.',
      'Developed RAG workflows with LangChain, GPT-4, Vertex AI and Pinecone, including query normalization, metadata filtering and grounded context assembly.',
      'Designed structured output contracts for answers, citations, document metadata, validation outcomes and error responses.',
      'Built rule-based, regex and named-entity validation services to catch PII, restricted content, unsupported statements and malformed outputs.',
      'Implemented controlled fallbacks for weak retrieval, missing context, low-confidence results, LLM outages and timeouts.',
      'Established prompt and RAG evaluation workflows across retrieval relevance, factual grounding, source accuracy and hallucination risk.',
      'Developed Spring Boot REST APIs for authentication, authorization, transaction workflows and session management with OAuth2, JWT and RBAC.',
      'Added operational telemetry for retrieval latency, LLM latency, token usage, validation results and Java-to-Python failure paths.',
      'Supported Docker containerization, Kubernetes deployment and Jenkins CI/CD with environment promotion and post-release monitoring.',
    ],
    metrics: [
      { value: 91, suffix: '%', label: 'RAG retrieval accuracy (from ~78%)' },
      { value: 40, suffix: '%', label: 'Fewer hallucinated responses' },
      { value: 2, suffix: 'M+', label: 'Embeddings indexed in Pinecone' },
      { value: 99.9, suffix: '%', label: 'API availability' },
    ],
    stack: [
      'Python',
      'FastAPI',
      'GPT-4',
      'LangChain',
      'RAG',
      'Pinecone',
      'Vertex AI',
      'BigQuery',
      'PostgreSQL',
      'Java 17',
      'Spring Boot',
      'Microservices',
      'REST APIs',
      'React',
      'TypeScript',
      'OAuth2 / JWT',
      'Docker',
      'Kubernetes',
      'Jenkins',
      'Cloud Monitoring',
      'pytest',
      'JUnit',
      'Mockito',
    ],
  },
  {
    id: 'ucm',
    kind: 'education',
    company: 'University of Central Missouri',
    role: 'M.S., Big Data Analytics & Information Technology',
    location: 'Warrensburg, Missouri',
    period: 'May 2023 — May 2025',
    start: '2023-05',
    end: '2025-05',
    accent: 'silver',
    headline:
      'Formalised the data and ML foundation behind the move from enterprise backend into applied AI.',
    summary: [
      'Graduate study in big data analytics and information technology, bridging the production engineering background built at LTIMindtree and ADP with the Generative AI work that followed.',
    ],
    highlights: [],
    metrics: [],
    stack: ['Big Data Analytics', 'Information Technology'],
  },
  {
    id: 'adp',
    kind: 'work',
    company: 'ADP',
    role: 'Software Engineer — Machine Learning, NLP & Backend Integration',
    location: 'Hyderabad, India',
    period: 'Jul 2021 — Apr 2023',
    start: '2021-07',
    end: '2023-04',
    accent: 'cyan',
    headline:
      'Machine learning, NLP and early Generative AI for enterprise payroll, HR and workforce analytics.',
    summary: [
      'Worked on an enterprise HR, payroll-intelligence and employee-support platform that combined machine learning, NLP, data engineering, semantic retrieval, Generative AI prototypes and enterprise Java integration.',
      'Took models from experimentation notebooks to reusable services — repeatable pipelines, testable components and integration-ready FastAPI endpoints consumed by Spring Boot systems.',
    ],
    highlights: [
      'Built NLP pipelines with BERT and SpaCy to extract skills, named entities, structured fields and employment attributes from HR documents.',
      'Developed data-processing pipelines with Pandas, Spark, PySpark and Airflow, loading curated outputs into PostgreSQL.',
      'Created Airflow workflows with task dependencies, scheduling, retries, failure handling and operational monitoring.',
      'Developed and evaluated models with scikit-learn, XGBoost and LightGBM for attrition, workforce analytics and payroll-anomaly detection.',
      'Applied SHAP feature attribution and model-review artifacts so auditors, compliance stakeholders and HR users could interpret predictions.',
      'Built FastAPI endpoints exposing NLP extraction, workforce predictions and anomaly scores to downstream applications.',
      'Designed semantic-retrieval prototypes with FAISS and Pinecone over approved HR policies, payroll documentation and benefits information.',
      'Prototyped Generative AI workflows with GPT-3 and T5 for payroll-exception summaries, benefit explanations and HR-policy answers.',
      'Implemented PII masking, role-aware access control, audit logging and AWS IAM policies over sensitive employee and payroll data.',
      'Automated model packaging, experiment tracking and deployment with Docker, Jenkins and MLflow.',
    ],
    metrics: [
      { value: 10, suffix: 'M+', label: 'Payroll & HR records processed' },
      { value: 45, suffix: '%', label: 'Reduction in ETL execution time' },
      { value: 95, suffix: '%', label: 'Entity-extraction accuracy (92–95%)' },
      { value: 89, suffix: '%', label: 'Attrition prediction accuracy' },
    ],
    stack: [
      'Python',
      'BERT',
      'SpaCy',
      'scikit-learn',
      'XGBoost',
      'LightGBM',
      'GPT-3',
      'T5',
      'FAISS',
      'Pinecone',
      'FastAPI',
      'Spark',
      'PySpark',
      'Pandas',
      'Airflow',
      'PostgreSQL',
      'Java',
      'Spring Boot',
      'MLflow',
      'SHAP',
      'Docker',
      'Jenkins',
      'AWS IAM',
    ],
  },
  {
    id: 'ltimindtree',
    kind: 'work',
    company: 'LTIMindtree',
    role: 'Java Full Stack Developer — ML Project Contributions',
    location: 'Hyderabad, India',
    period: 'Aug 2018 — Jun 2021',
    start: '2018-08',
    end: '2021-06',
    accent: 'silver',
    headline:
      'The enterprise-engineering foundation: secure Java microservices for healthcare and insurance claim processing.',
    summary: [
      'Developed Java and Spring Boot microservices for enterprise healthcare and insurance claim-processing applications, plus the Angular and React interfaces on top of them.',
      'Later in the role, contributed to machine-learning initiatives — preparing claims and patient-related features, prototyping risk-scoring and anomaly-detection models, and integrating selected model outputs back into Java services.',
    ],
    highlights: [
      'Built REST APIs for claim workflows, application validation, workflow-status processing and downstream integrations.',
      'Implemented layered controller / service / validation / integration / data-access components with versioned API contracts.',
      'Built Angular and React interfaces in TypeScript, wired to Spring Boot APIs.',
      'Implemented OAuth2, JWT authentication and role-based access control for protected enterprise features.',
      'Integrated Apache Kafka and RabbitMQ for asynchronous communication, event-driven processing and retry mechanisms.',
      'Tuned Oracle SQL, PL/SQL stored procedures, indexes and execution plans to resolve concurrency bottlenecks.',
      'Containerized services with Docker and supported deployments to Azure Kubernetes Service via Jenkins pipelines.',
      'Used Elasticsearch-based centralized log search to investigate API failures, messaging problems and production incidents.',
      'Prepared approved data features for risk-scoring and anomaly-detection prototypes and integrated model outputs through REST endpoints.',
      'Created Tableau and Power BI dashboards for model-informed risk indicators, exceptions and operational measures.',
    ],
    metrics: [
      { value: 100, suffix: 'K+', label: 'Claims processed per month' },
      { value: 35, suffix: '%', label: 'Faster query response time' },
      { value: 25, suffix: '%', label: 'Kafka consumer throughput gain' },
      { value: 40, suffix: '%', label: 'Reduction in deployment time' },
    ],
    stack: [
      'Java',
      'Spring Boot',
      'Microservices',
      'REST APIs',
      'Angular',
      'React',
      'Redux',
      'TypeScript',
      'Apache Kafka',
      'RabbitMQ',
      'Oracle PL/SQL',
      'OAuth2 / JWT',
      'Docker',
      'Azure Kubernetes Service',
      'Jenkins',
      'JUnit',
      'Mockito',
      'Elasticsearch',
      'scikit-learn',
      'Tableau',
      'Power BI',
    ],
  },
];

/** Compact company strip rendered in the hero. */
export const COMPANIES = ['American Express', 'ADP', 'LTIMindtree'] as const;
